universe = parallel

executable = jobs/openmpiscript.sh

arguments = ./KMEANS_omp_mpi input100D2.inp 40 100 1 0.0001 output100D2.txt comp_time100D2.csv 2

should_transfer_files = YES

transfer_input_files = KMEANS_omp_mpi, test_files/input100D2.inp 

output = jobs/logs_omp_mpi/out.$(NODE)

error = jobs/logs_omp_mpi/err.$(NODE)

log = jobs/logs_omp_mpi/log

machine_count = 1

request_cpus = 32

getenv = True

queue
